### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by redcapua** [ambrosus/sdk-ios#1]
Hi!

I met very strange issue related to this library.

My project is created with Objective-C.

I created Podfile:
=========

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'justtest' do
    pod 'AmbrosusSDK'
end

=========

After 'pod install' I opened project into XCode and got this issue 

![screen shot 2018-11-25 at 10 52 17 am](https://user-images.githubusercontent.com/9165541/48977358-60d87700-f0a1-11e8-9392-377df643020e.png)

It seems library has not been tested with XCode :(

**Comment by allgamesallfree** [comment]
The SDK is written in Swift 4.0 and requires that apps using it are built in Xcode 9.0 and later. You will see the above message or a similar one in Xcode 8 and Xcode 7. We have no plans to add support for older versions of Xcode. Supported Xcode and Swift versions are detailed in the main README:
https://github.com/ambrosus/sdk-ios

**Comment by redcapua** [comment]
I am using the latest version of Xcode for today


![screen shot 2018-11-25 at 6 31 20 pm](https://user-images.githubusercontent.com/9165541/48981604-643f2300-f0e0-11e8-99ed-b174605236b3.png)
